# To run locally
# npx @techdocs/cli serve -v -c ./mkdocs.yml
# 
site_name: 'crocochrome Internal Documentation'
repo_url: https://github.com/grafana/crocochrome
edit_uri: edit/main/docs
docs_dir: doc

theme:
  name: material
  features:
    - navigation.sections

plugins:
  - techdocs-core
