name: Publish container

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for the version script to work.
      - name: Compute repo metadata
        id: repo
        run: |-
          echo "version=$(./scripts/version)" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
      # grafana/shared-workflows/actions/push-to-gar-docker runs setup-buildx, but not setup-qemu.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: |-
            ghcr.io/${{ github.repository }}:${{ steps.repo.outputs.version }}
          push: true
          platforms: linux/amd64,linux/arm64
